server:
  port: 0

spring:
  application:
    name: snippet-service
  cassandra:
    port: 9042
    contact-points: snippetDatabase
    keyspace-name: snippetsKeyspace
    entity-base-package: ru.micro.DAO

