openapi: "3.0.3"
info:
  title: "Social_network_with_photos API"
  description: "Social_network_with_photos API"
  version: "1.0.0"
servers:
  - url: "https://Social_network_with_photos"
paths:
  /posts/{postId}/comments:
    get:
      summary: "Получить список комментариев"
      operationId: "getCommentsPost"
      parameters:
        - name: "postId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CommentResponse"
    post:
      summary: "Добавить комментарий"
      operationId: "createCommentPost"
      parameters:
        - name: "postId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "id"
          in: "header"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              type: "string"
        required: true
      responses:
        "200":
          description: "OK"
    delete:
      summary: "Удалить комментарий"
      operationId: "removeCommentPost"
      parameters:
        - name: "postId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "id"
          in: "header"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              type: "string"
              format: "uuid"
        required: true
      responses:
        "200":
          description: "OK"
components:
  schemas:
    Timestamp:
      type: "object"
      properties:
        nanos:
          type: "integer"
          format: "int32"
    CommentResponse:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        postId:
          type: "string"
          format: "uuid"
        userId:
          type: "integer"
          format: "int32"
        userName:
          type: "string"
        text:
          type: "string"
        createdAt:
          $ref: "#/components/schemas/Timestamp"