server:
  port: 0

spring:
  application:
    name: post-upload-service
  cassandra:
    port: 9042
    contact-points: socialNetworkDatabase
    keyspace-name: socialNetworkKeyspace
    entity-base-package: ru.micro.DAO