server:
  port: 0

spring:
  application:
    name: recommendation-service
  cassandra:
    port: 9042
    contact-points: socialNetworkDatabase
    keyspace-name: socialNetworkKeyspace
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neoneoneo

