server:
  port: 0

spring:
  application:
    name: user-service

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neoneoneo

jwt:
  secret: MySecretCodeThatIsLongerThanBefore

