server:
  port: 0

spring:
  application:
    name: photo-upload-service
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  cassandra:
    port: 9042
    contact-points: socialNetworkDatabase
    keyspace-name: socialNetworkKeyspace
