create table users (
    id integer primary key generated by default as identity,
    password varchar not null check (length(password) > 0),
    name varchar not null unique check ( length(name) > 0 ),
    role varchar not null check (length(role) > 0)
);