version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5446
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data